[project]
name = "uta-gms-reduced"
version = "0.1.0"
description = "Dimensionally reduced robust and stochastic ordinal regression."
readme = "README.md"
dependencies = [
    "umap-learn>=0.5.7",
]

[tool.ruff]
line-length = 120
